### ISSUE TITLE
Selector should have 2 arguments

### ISSUE THREAD

**Issue by budarin** [edriang/use-context-selection#3]
Please fix declaration

Selector should have 2 arguments:
- state
- own component Props

**Comment by adrian-marcelo-gallardo** [comment]
Hi! Please, consider the next example:

Let's suppose we have stored in our Context a Map `resultsByCategory` which keys are the names of categories and its values are the results to display for a given category.

Now, let's suppose we have this `CategoryResults` component, which is in charge of rendering the results for a given `categoryName` received as prop:

```
const CategoryResults = ({ categoryName }) => {
  const { results } = useContextSelection(Context, ({ resultsByCategory }) => ({
     results: resultsByCategory[categoryName],
  });

  return (
    <div>
      <h1>Results for category: {categoryName}</h1>
      <pre>{JSON.stringify(results, null, 2)}</pre>
    </div>
  )
}
```

As hooks are intended to be called in the body of Functional components, you already can access to component's props as they are in the same Scope.

Do you have in mind any other use case?

**Comment by budarin** [comment]
Hi!

Usually we use selectors in ducks files like so:

counter.js
```js
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';

export selector = (state, id) => state.counters[id];
...
```

and then
CounterContainer.js
```jsx
import Context from './context'
import { selector } from './counter.js'

const CounterContainer = ({ id }) => {
    const { results } = useContextSelection(Context, state => selector(state, id));

    return ...;
}
```

**Comment by budarin** [comment]
I'm sorry - I confused the declaration of a normal selector with a selector for context :)
