### ISSUE TITLE
React 17 in peer dependencies

### ISSUE THREAD

**Issue by mjfwebb** [edriang/use-context-selection#5]
```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from use-context-selection@1.4.2
npm ERR! node_modules/use-context-selection
npm ERR!   use-context-selection@"^1.4.2" from the root project
```

Would be nice to change the peer dependency to include React 17. I haven't noticed any issues with using React 17 so far, but there could possibly be so.

**Comment by edriang** [comment]
Hello there! sorry for the delay, I was on vacation. 

Your request seems reasonable, I just published the library with the updated constrains.

I'll close the issue, but feel free to ping me again in case something goes wrong.
